### ISSUE TITLE
Escaping character data when merging EPG files

### ISSUE THREAD

**Issue by maciekz** [matthuisman/plugin.program.iptv.merge#10]
Hi,

I've noticed that character data is not being escaped when writing to the merged EPG file. If in source file there's a title like "Tom & Jerry" the result XML file is broken as there's

`Tom & Jerry`

instead of 

`Tom &amp; Jerry`

Best regards!

**Comment by matthuisman** [comment]
Fixed in version 0.3.9

**Comment by maciekz** [comment]
Thank you very much! :)
