### ISSUE TITLE
Kodi Matrix - Compatibility - Kodi Addon Repo

### ISSUE THREAD

**Issue by phunkyfish** [matthuisman/plugin.program.iptv.merge#12]
Hey @matthuisman,

Just wanted to start an issue to catch any conversation related to the Matrix version for IPTV Simple Client and to discuss anything that would make them work better together.

In addition also wanted to ask if you would be interested in submitting the addon to the kodi repo? This would mean users would not need to install another repo to get the addon, making access to it easier and we would then have an official addon for merging IPTV.

From what I gather (I've never submitted an addon myself), you are still the maintainer etc. it just means it's easier for users.

Entirely up to you of course.

Cheers

**Comment by phunkyfish** [comment]
Also, would you like to join the kodi slack as a guest? It would make conversing easier?

**Comment by matthuisman** [comment]
Sure, my slack email is: slack@matthuisman.nz
Do you send me an invite?

Thing that I most need is a way to tell IPTV to reload it's data....
Is there any possible way?

**Comment by phunkyfish** [comment]
Yes, will get an invite sent later today.

We’ll find a way we just need to make sure we can protect playback for users with older devices. Right now it’s just really simple, every X minutes, refresh.

**Comment by phunkyfish** [comment]
How do you currently change the iptvsimple addon settings, or do you modify them at all?

**Comment by phunkyfish** [comment]
One thing I would like to be able to do is call iptvmerge from iptvsimple for things like referenced M3Us. Not sure if that’s doable or not.

**Comment by bam80** [comment]
> Thing that I most need is a way to tell IPTV to reload it's data....

> Right now it’s just really simple, every X minutes, refresh.

What if X occurs while writing XMLTV by iptv.merge? Is it handled somehow?

**Comment by phunkyfish** [comment]
No it’s not. They would need to be synced. So merge the files at 10 minutes past the hour and load them at 20 mins past. Or something like that.

**Comment by bam80** [comment]
So if the XML happens to be in-process and incomplete, won't it broke EPG in the database?
Will it just load partially, until next time, preserving data already exist?

**Comment by phunkyfish** [comment]
File operations are atomic on most platforms.

One of a number of things could happen depending on approach.

1) The file will be open for writing and it won’t load, so no change (this would be a poor implementation approach). 
2) The file will be copied at the end, and the read must wait for the copy to compete (enforced by the OS).
3)The file won’t load as it incomplete. I.e. it’s written to in chunks.
4) A new file is created and the settings are changed to reflect this so on the next load it reads a new file.

**Comment by bam80** [comment]
> One of a number of things could happen depending on approach.

I'm aware of the theory. Just wondered what happens actually.

**Comment by phunkyfish** [comment]
None of this exists. There is no actual yet.
