### ISSUE TITLE
[question] Compatibility with IPTVMerge

### ISSUE THREAD

**Issue by Sorien** [matthuisman/plugin.program.iptv.merge#14]
i see that i need .iptv_merge but i want to be sure that there is no missing piece. 

1. is it enough to create such file?

```json
{
    "version":  3,
    "playlist": "plugin://$ID/generate-playlist/$FILE",
    "epg":      "plugin://$ID/generate-rpg/$FILE"
}
```
iptvmerge will call these url and wait (there is some timeout like 60*8s) for plugin to create these files.

2. i'm automatically configuring iptvsimple so is there any way how to detect that iptvsimple is configured with iptvmerge?

**Comment by matthuisman** [comment]
You need to call 
`xbmc.executebuiltin('Skin.SetString(merge,started)')` when the merge starts then
`xbmc.executebuiltin('Skin.SetString(merge,ok)')` once it's done
or `xbmc.executebuiltin('Skin.SetString(merge,error)')` if it fails

My add-ons use a common decorator like below
```
def merge():
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            xbmc.executebuiltin('Skin.SetString(merge,started)')

            try:
                result = f(*args, **kwargs)
            except Exception as e:
                xbmc.executebuiltin('Skin.SetString(merge,error)')
            else:
                xbmc.executebuiltin('Skin.SetString(merge,ok)')
                return result
                
        return decorated_function
    return lambda f: decorator(f)
```

Then I just do

```
@merge()
def generate-playlist(output):
   #do_stuff
```
