### ISSUE TITLE
#EXTVLCOPT

### ISSUE THREAD

**Issue by 4Magma** [matthuisman/plugin.program.iptv.merge#3]
I merge two m3u from AVM Fritz!Box 6490 DVB-C
which contain a 
#EXTVLCOPT:network-caching=1000
line after each 
#EXTINF:0, {Channelname}
line.

Could you please automatical filter this lines out?

Each line appears else as duplicate of the channel in the #EXTINF-line above.
Hide Channel on one of this duplicates hides all of them.

**Comment by matthuisman** [comment]
This should be fixed in 0.2.2 of the add-on that I just pushed.
https://github.com/matthuisman/plugin.program.iptv.merge/commit/68506422b680e6eaddd8c75a1a9c925a1e56a1ec#diff-34e69a566e88084716834b66430ef54aR150
