### ISSUE TITLE
EPG-IDs

### ISSUE THREAD

**Issue by 4Magma** [matthuisman/plugin.program.iptv.merge#4]
Could you please:
1. create list of channel ids and names from epg data
   <channel id="{channel id}">
      <display-name lang="de">{channel name}</display-name> 
   </channel>

2. in channel manger
 - show as {channel name} (group title) [channel id]
 - in context menu "channel epg|tvg id" (select from list from 1.)
 - highlight channel ids for channel which are not in list from 1.

**Comment by matthuisman** [comment]
I don't understand this...

**Comment by 4Magma** [comment]
from epg.xml:
- extract id attribute of channel tags and cdata of display-name tags.
- create a list of channel id and channel name
- optional: sort by channel name

in channel manager:
- show tvg-id attribute in [] behind (group-title)
- show tvg-id in a different color if in conflict with list from epg.xml (if it not exists there)
- add option to context menu to set tvg-id (let user choose from list from epg.xml)

P.S.:
with the csv export/import suggested in a another comment i could set
tvg-id myself and would not really need this feature.

**Comment by matthuisman** [comment]
As some of the EPGS can get very large, I don't actually parse them.
And I don't want to start parsing them.
So, I'll close this as won't happen and look into import / export overrides

**Comment by matthuisman** [comment]
Actually, let's take another look at this.

Can you tell me what you are trying to do?
Playlists and EPGs should already be linked.

Do you have playlist channels that you are trying to link to EPG?

The way it works is that in the playlist.m3u8, there is tvg-id.
If kodi finds a matching tvg-id in the epg file, then it uses that programs.

Playlist
`#EXTM3U
#EXTINF:-1 tvg-logo="https://i.mjh.nz/nz/images/tv.9.png" tvg-id="tv.9" tvg-chno="1",TVNZ 1
https://i.mjh.nz/nz/tv.9.m3u8`

Epg
```
<channel id="tv.9"><display-name>TVNZ 1</display-name></channel>
.....
<programme channel="tv.9" start="20190730183145 +0000" stop="20190730200510 +0000"><title>Fandom</title></program>
```

I looked at my xml code and I can grab the id= from channel.
Then add them to a list.
Then in channel manager, show if a channel has a linked epg.

**Comment by 4Magma** [comment]
- merge two m3u from fritz!box dvb-c receiver (via direct download url)(hd+sd)
- these contain no tvg-id

- display name only in case there are tvg-ids, which end up in a
  other position in sorted list as expected

**Comment by matthuisman** [comment]
Oh right.
I see.

For now I'll add support for setting tvg-id in channel manager (just text
entry).
This is easy to do.

Next step is to instead of text entry, have it show a  list of tvg-ids it
has found in the epgs.
(Saves typos etc)

Have that select list also show the name of that channel from the EPG to
make it easier to spot correct channel.

Preselect the best match based on playlist channel name and EPG channel
name.

Have this list also advise which tvg-id is already assigned.

Also have the main channel list in channel manager show (No EPG) for
channels without a matching EPG entry.

**Comment by matthuisman** [comment]
just pushed 0.2.9 that adds everyhing I mentioned in last comment.
