### ISSUE TITLE
csv export/import of overrides.json data

### ISSUE THREAD

**Issue by 4Magma** [matthuisman/plugin.program.iptv.merge#5]
to avoid to edit the channel logo and xmltv id for each channel manually,
i converted the overrides.json via notepad++ to csv format and
imported it into libre office calc.

**Could you add an csv import/export feature for overrides.json
so this way of external editing would easier possible.**

- Head for example:  _url;_name;_hidden;group-title;tvg-name;tvg-logo
- empty fields could be skipped/ignored
- pass through unknown columns as attributes like
  tvg-logo as "tvg-logo": "...." in #EXTINF line
- on export fill allways _name to identify the channel
   on import remove _name if identical with original name

Edit:
successful merged m3u with tvg-id's from manipulated overrides.json
so pass through is already possible.

**Comment by matthuisman** [comment]
This is won't do.
JSON format is easy to work with. 
Just use any text editor
