### ISSUE TITLE
Huge file merge complete - never start pvr client

### ISSUE THREAD

**Issue by ozzymanborn** [matthuisman/plugin.program.iptv.merge#8]
I have a huge file. (Merge playlist thing says 15.9 MB) with 202MB xml epg. Merge is completed without issues. But when It's restarted pvr manager it's stuck on PVR Manager is Starting up. Loading channels from clients part.

I don't know it's issue of your addon or issue of iptv simple client. But I just wanted to give a heads up.

Btw I will try without epg. I will check which of these making issue.

**Comment by matthuisman** [comment]
Try using the file directly in Simple Client (not via merge)
That will tell you where the problem is.
If it's in Simple Client, they are working on improving epg loading speeds
